### ISSUE TITLE
Use huggingface implementation 

### ISSUE THREAD

**Issue by CatStark** [jina-ai/executors#10]
This repository should switch from OpeanAI's to Huggingface's implementation of the model. This has several benefits

The transformers library is professionally developed and maintained - meaning us and the users can rely on it more. OpenAI's implementation is just research paper demonstration, with little resources allocated to continued development and maintenance.
Transformers library integrates with huggingface model hub, where custom versions of the model can be published - several already exist for CLIP. Users would appreciate the option to use custom model more suitable for their use case
Users training custom models will do so using the transformers library, which has a well developed training interface (OpeanAI's has none). Meaning that if we want to enable users to use their own custom models, we must use huggingface's implementation.
Since the default weights (ViT 32) are present in both implementations, there should be zero switching downside for existing users.

**Comment by makram93** [comment]
Hi @tadejsv 

I would like to work on this issue

**Comment by tadejsv** [comment]
Hi @makram93, thank you for your interest in contributing.

I would recommend you start with CLIPTextEncoder, as working with text data should be easier to start. You can take a look at the TransformerTorchEncoder, as in fact the setup there should be quite similar (they both use huggingface transformers).

If you need any help, please let me know

**Comment by makram93** [comment]
Thanks for the tip. I looked through the TransformerTorchEncoder and it returns embedding too. So if it already uses huggingface transformers and returns the text encoding then why do we need CLIPTextEncoder?

**Comment by tadejsv** [comment]
If you look at the source code of the CLIP model, you will see that to obtain text embeddings, a projection of the embeddings is also used: https://huggingface.co/transformers/_modules/transformers/models/clip/modeling_clip.html#CLIPModel.get_text_features

Therefore, our usual TransformerTorchEncoder can not be used in this case, so we still need CLIPTextEncoder

**Comment by makram93** [comment]
Thanks for the input. I have implemented the code for CLIPTextEncoder, taking reference from TransformerTorchEncoder. For testing, I am using the same unit_tests file as was used for OpenAI CLIP implementation. Please let me know the next steps.

**Comment by tadejsv** [comment]
Hey @makram93, I can not see the code that you have implemented. You should make a pull request to this repository.

**Comment by makram93** [comment]
Hi,

Following the guidelines for submission, I ran `pre-commit install`. However, on committing my code, I get the following error: "No .pre-commit-config.yaml file was found". Can you suggest which yaml file to use for this repo?

**Comment by tadejsv** [comment]
Here is the pre commit config that jina uses: https://github.com/jina-ai/jina/blob/master/.pre-commit-config.yaml

**Comment by makram93** [comment]
Hi @tadejsv, I have raised the PR.

**Comment by makram93** [comment]
Hi @tadejsv, I have committed the code with changes :)

**Comment by tadejsv** [comment]
Thanks, will get back to you soon

**Comment by tadejsv** [comment]
Thank you for the contribution on the CLIP Text Encoder, @makram93 !

Do you feel like tackling the image encoder as well? If so, let me know and I'll give you some initial guidelines. But if you don want to no worries, I can take over this one :)

**Comment by makram93** [comment]
Hi @tadejsv,

I am happy to contribute and would like to work on the image encoder as well.

**Comment by tadejsv** [comment]
Great, that's the spirit! :)

So, some tips for that:
- about the executor itself, maybe look a bit a AudioCLIPImageEncoder that I added recently. But your executor will be different, as we don't use the transformers package in that encoder.
- for documentation you can also look at AudioCLIPImageEncoder, but you can take out everything regarding downloading the model and volumes, as they won't be necessary here
- for tests, adapt them from AudioCLIPImageEncoder. The one that is really important is the one that compares embeddings from different images - feel free to just copy that. Also, just like in the text encoder, we need a test here to make sure the embeddings are the same as with the OpenAI version of the model

And as always, if you get stuck anywhere, just let me know.

**Comment by makram93** [comment]
Hi @tadejsv 

I have one question regarding preprocessing that you implemented in AudioCLIPImageEncoder. If `use_default_preprocessing` is set to `False` then how do we enforce resize and normalization? Who or where it is being handled? After all, the model can only accept images of size `224`.

**Comment by tadejsv** [comment]
The assumption is that if `use_default_preprocessing=False`, the user has already preprocessed the images before. But actually, I really don't think this is a desirable option (I kept it in initially to mirror the CLIP Image encoder) - so let's drop it here.
