### ISSUE TITLE
SimpleIndexer does not work with Docker container

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/executors#116]
The simple indexer is currently experiencing a bug when running it with docker jinahub+docker://SimpleIndexer.
After closing the docker container, it sometimes happens that the stored memmap which is mounted into the container is corrupted. After data, the entire index is broken and the user needs to index from scratch.

The error does not happen when using jinahub://SimpleIndexer 

Originally found #100

**Comment by CatStark** [comment]
This was solved in 2.0.19
To avoid this problem use jina >= 2.0.19 and a recent simple indexer docker image
