### ISSUE TITLE
rename all `default_x`; sort out args; add default parameters

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/executors#216]
Here is a checklist for this ticket

- [ ] rename `default_traversal_paths` to `traversal_paths`
- [ ] rename `default_batch_size` to `batch_size`
- [ ] keep the args in the order `traversal_paths`, `batch_size`, `device`, `*args`, `**kwargs`
- [ ] add default parameters for the endpoint functions,  `docs: Optional[DocumentArray] = None` and `parameters: Dict = {}`  and check whether the function can handle `docs==None`

**Comment by bwanglzu** [comment]
- crafters
- encoders-audio
- encoders-video

**Comment by nan-wang** [comment]
The following encoders are left for next week to avoid Breaking changes during the weekend.
- CLIPTextEncoder, 
- TransformerTFTextEncoder, 
- TransformerTorchEncoder
- CLIPImageEncoder

**Comment by CatStark** [comment]
Closing this one and we will create a new one for indexers after theOneIndexer is ready

The missing ones are:

- [ ] indexers-doccache
- [ ]  indexers-merger
- [ ]  indexers-searcher
- [ ] indexers-storage
