### ISSUE TITLE
Encode/decode for different executors 

### ISSUE THREAD

**Issue by CatStark** [jina-ai/executors#240]
| Done | Executor Name         | repository                                                                                | Reference                                                                                                                       | Asignee                |
| ---- | --------------------- | ----------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------- | ---------------------- |
| ✅ | `Mp3Loader`           | [`executor-audio-mp3loader`](https://github.com/jina-ai/executor-audio-loader)                                                                | https://github.com/jina-ai/examples/blob/master/audio-to-audio-search/executors.py#L79:L97                                      | @jakob1111996          |
| ✅ | `WavLoader`           | [`executor-audio-wavloader`](https://github.com/jina-ai/executor-audio-loader)                                                                | https://github.com/jina-ai/examples/blob/master/audio-to-audio-search/executors.py#L79:L97                                      | @jakob1111996          |
| ✅   | `VideoFrameLoader`    | [executor-video-frameextractor](https://github.com/jina-ai/executor-video-frameextractor), [executor-video-loader](https://github.com/jina-ai/executor-video-loader) | https://github.com/jina-ai/eap-google-ads/blob/main/pods/executors.py#L47:L112                                                  | @makram93  & @nan-wang |
|✅   | `VideoAudioLoader`    | [executor-audio-frameloader](https://github.com/jina-ai/executor-video-loader)                                                             | https://github.com/jina-ai/eap-google-ads/blob/main/pods/executors.py#L47:L112                                                  | @makram93              |
|✅    | `VideoSubtitleLoader` |[ `executor-subtitle-frameloader` ](https://github.com/jina-ai/executor-video-loader)                                                          | https://github.com/jina-ai/eap-google-ads/blob/main/pods/executors.py#L47:L112                                                  | @makram93              |
| ✅   | `PptxLoader`          | [executor-pptxloader](https://github.com/jina-ai/executor-pptxloader)                     | https://support.microsoft.com/en-us/office/extract-files-or-objects-from-a-powerpoint-file-85511e6f-9e76-41ad-8424-eab8a5bbc517 | @cristianmtr           |

-----
## Reference
- [How to Build an in-house Executors](https://docs.google.com/document/d/1tTc5oVFqAWQlFjuV5NPS-JbknV8_2Ooe_7EF3jpZQK0/edit#heading=h.jb8g4buzk04m)

**Comment by jakob1111996** [comment]
Just to understand this correctly: Do we want one executor that can read every data type or should we have separate executors for separate data types? @CatStark @nan-wang

**Comment by nan-wang** [comment]
> Just to understand this correctly: Do we want one executor that can read every data type or should we have separate executors for separate data types? @CatStark @nan-wang

Yes, exactly

**Comment by maximilianwerk** [comment]
The main point here is, that it is not just a data loader from somewhere but at the same time a decoder. E.g. the `Mp3Decoder` should:

- if buffer is empty, call `convert_uri_to_buffer` (and load data from disk/anywhere in the internet)
- afterwards transform the buffer into a time series of frames.

**Comment by maximilianwerk** [comment]
Decision from alignment meeting: We should have one Decoder/Loader per media type for now. One `AudioLoader` and one `VideoLoader`.

**Comment by jakob1111996** [comment]
> 
> 
> > Just to understand this correctly: Do we want one executor that can read every data type or should we have separate executors for separate data types? @CatStark @nan-wang
> 
> @jacobowitz sorry, I read the message wrongly. For loading each type, We want to have one executor.

Alright, I understand :) Btw, I am @jakob1111996, not @jacobowitz (This would be Tobias)

**Comment by makram93** [comment]
> Decision from alignment meeting: We should have one Decoder/Loader per media type for now. One `AudioLoader` and one `VideoLoader`.

Hi @jakob1111996, in yesterday's meeting we decided to have one executor per mime type. So, overall three executors - audio, video, and pptx. I will be working on this ticket too and am picking up video executors if you haven't started with video already. Just wanted to let you know so that we both don't end up doing the same work. :)

**Comment by jakob1111996** [comment]
Nice @makram93 , I have started working on Audio, so we should be fine :)

**Comment by makram93** [comment]
@nan-wang, after discussion with @florian-hoenicke, we decided to skip the subtitle encoder for now as we don't see any use case currently.

**Comment by jakob1111996** [comment]
For the audio reader, which data types should be supported? Right now, I am supporting MP3 and WAV. Any other types you think are necessary? AIFF, WEBM, FLAC, AAC, WMA, MP4, M4A? @nan-wang @makram93 @maximilianwerk

**Comment by nan-wang** [comment]
> For the audio reader, which data types should be supported? Right now, I am supporting MP3 and WAV. Any other types you think are necessary?
I suggest not supporting other types at the moment. Let's see what are requested by the community re after launching the hub.

**Comment by nan-wang** [comment]
> after discussion with @florian-hoenicke, we decided to skip the subtitle encoder for now as we don't see any use case currently
We are actually using this in one of the EAPs although this part is currently implemented by the user.

**Comment by florian-hoenicke** [comment]
> We are actually using this in one of the EAPs although this part is currently implemented by the user.



@nan-wang  okay, I see. What video source files should be supported for subtitles?

**Comment by nan-wang** [comment]
> okay, I see. What video source files should be supported for subtitles
Let's focus on `.mp4` and save the outputs at `.srt` using `ffmpeg`.
