### ISSUE TITLE
Add FrameExtractor to Hub

### ISSUE THREAD

**Issue by CatStark** [jina-ai/executors#247]
Related code https://github.com/jina-ai/example-video-search/blob/main/executors.py#L23:L110

**Comment by CatStark** [comment]
Related PR: https://github.com/jina-ai/executor-video-frameextractor/pull/2

**Comment by makram93** [comment]
Related PR: [jina-ai/executor-video-frameextractor/#3](https://github.com/jina-ai/executor-video-frameextractor/pull/3)
