### ISSUE TITLE
DocCache rewrite

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/executors#254]
We have removed `content_hash` field from `Document`.

The logic needs to be reimplemented in the `DocCache` to keep it working with latest version of Jina.

**Comment by gauthamsuresh09** [comment]
Hi @cristianmtr, I was looking at this issue. The `content_hash` still exists in `Document`, not as a field but instead as a `property`. So, I'm not sure about the change you are proposing, because the code should work same as before.

**Comment by cristianmtr** [comment]
Yes you're right. Ran a test PR and all good. https://github.com/jina-ai/executors/pull/258
