### ISSUE TITLE
FaissPostgresIndexer: failed to sync at startup

### ISSUE THREAD

**Issue by numb3r3** [jina-ai/executors#275]
When some documents' embeddings are None, the `sync` cannot work at startup.

**Comment by cristianmtr** [comment]
Do you have a minimal example?

**Comment by numb3r3** [comment]
For example:
1. First, start a new index flow
    a. index 1000 docs
    b. soft-delete some docs

2. Then, start a new search flow
    a. syc with delta only (raise exception)
          - Reason: the soft-deleted documents are also been considered
