### ISSUE TITLE
Refactoring of DocumentArrayInMemory affects TransformerSentenceEncoder

### ISSUE THREAD

**Issue by ugm2** [jina-ai/executors#319]
Updates on DocumentArrayInMemory where `get_attributes` has become private access in [this update](https://github.com/jina-ai/docarray/blob/97866c6dc27602364f76d7e582c3c26be40f7b99/CHANGELOG.md#-code-refactoring) which has made TransformerSentenceEncoder outdated as its class is accessing [`get_attributes`](https://github.com/jina-ai/executors/blob/c9bffccc8f97dc33128c48db7a0f69336448008e/jinahub/encoders/text/TransformerSentenceEncoder/sentence_encoder.py#L57)

The error thrown is:
```
AttributeError: 'DocumentArrayInMemory' object has no attribute 'get_attributes'
```

**Comment by nan-wang** [comment]
@samsja @JoanFM https://github.com/jina-ai/executor-sentence-transformer/pull/7 Here is the PR

**Comment by JoanFM** [comment]
Hey @ugm2 ,

This executor has already been migrated
