### ISSUE TITLE
Clean-up README in executors

### ISSUE THREAD

**Issue by CatStark** [jina-ai/executors#40]
LIST:

- [] [image-torch-object-detection-segmenter ](https://github.com/jina-ai/executors/tree/main/jinahub/segmenters/TorchObjectDetectionSegmenter)
- [] i[mage-normalizer ](https://github.com/jina-ai/executors/tree/main/jinahub/crafters/ImageNormalizer)
- [] [text-sentencizer ](https://github.com/jina-ai/executors/tree/main/jinahub/segmenters/Sentencizer)
- [] [text-audioclip-text-encoder](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/text/AudioCLIPTextEncoder)
- [] [image-audioclip-image-encoder](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/image/AudioCLIPImageEncoder)
- [] [clip-image](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/image/CLIPImageEncoder)
- [] [audio-clip-encoder](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/audio/AudioCLIPEncoder)
- [] [text-clip-text-encoder](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/text/CLIPTextEncoder)
- [] [pdf-crafter](https://github.com/jina-ai/executors/tree/main/jinahub/segmenters/PDFSegmenter)
- [] [yolov5](https://github.com/jina-ai/executors/tree/main/jinahub/segmenters/YoloV5Segmenter)
- [] [indexers](https://github.com/jina-ai/executors/tree/main/jinahub/indexers)
- [] [image-torch-encoder ](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/image/ImageTorchEncoder)
- [] [text-transformer-tf-encoder ](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/text/TransformerTFTextEncoder)
- [] [audio-VGGishEncoder](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/audio/VGGISHAudioEncoder) 
- [] [sentence-transformer](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/text/TransformerSentenceEncoder) 
- [] [image-custom-torch-encoder ](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/image/CustomImageTorchEncoder)
- [] [image-paddle-encoder ](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/image/ImagePaddlehubEncoder)
- [] [big-transfer-encoder ](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/image/BigTransferEncoder)
- [] [image-tf-encoder ](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/image/ImageTFEncoder)
- [] [transformer-torch-encoder ](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/text/TransformerTorchEncoder)
- [] [text-spacy-encoder ](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/text/SpacyTextEncoder)
- [] [text-flair-encoder](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/text/FlairTextEncoder)
- [] [text-paddle](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/text/TextPaddleEncoder)
- [] [video-torch-encoder ](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/video/VideoTorchEncoder)
- [] [laser-encoder](https://github.com/jina-ai/executors/tree/main/jinahub/encoders/text/LaserEncoder)

**Comment by jakob1111996** [comment]
I think this was done by #41
