### ISSUE TITLE
feat: add GPU support for executors

### ISSUE THREAD

**Issue by jakob1111996** [jina-ai/executors#44]
We need to have GPU support for many of the executors (especially encoders) to reduce runtime.

These steps need to be done in advance:
- [x] Enable tag support in hubble @mapleeit 
- [x] Enable multi-docker image support in hubble/core
- [x] Setup GPU machine as test runner
- [x] Update CI to run GPU tests on GPU runner
- [x] Decide on parameter name for gpu usage (device='cuda'/gpu=True/use_gpu=True/gpu=1 etc.)
- [x] Set up continuous deployment for GPU docker containers

For every executor, these things need to be done:
1. Add Dockerfile.gpu which can be user-defined
2. Add GPU tests marked to run only on GPU instance
3. Rename GPU parameter to device='cuda:1'/'cuda'/'cpu'
4. Add section to README (Installation + Usage)
5. Update Dockerfile versions to 2.0.20 and tests/requirements to ~=2.0
6. Push first version of GPU docker container to hubble

These executors need to be adapted:

Audio Encoders:
- [x] AudioCLIPEncoder
- [x] VggishAudioEncoder

Image Encoders:
- [x] AudioCLIPImageEncoder
- [x] BigTransferEncoder
- [x] CLIPImageEncoder
- [x] CustomImageTorchEncoder
- [x] ImagePaddlehubEncoder
- [x] ImageTFEncoder
- [x] ImageTorchEncoder

Text Encoders:
- [x] AudioCLIPTextEncoder
- [x] CLIPTextEncoder
- [x] DPRTextEncoder
- [x] FlairTextEncoder
- [x] LaserEncoder
- [x] SpacyTextEncoder
- [x] TextPaddleEncoder
- [x] TFIDFTextEncoder
- [x] TransformerSentenceEncoder
- [x] TransformerTFTextEncoder
- [x] TransformerTorchEncoder

**Comment by tadejsv** [comment]
A jina image with docker installed is not possible. Installing CUDA is tricky, and every deep learning framework does it differently (e.g. pytorch uses conda, TF does not).

Also, for the GPU argument in the executor: also differs across DL frameworks (in pytorch you have "device" for each model, in TF I think you actually have to do it globally). Let's just leave it like that. For that reason, config_gpu etc. is not needed.

**Comment by tadejsv** [comment]
This points were also made by @numb3r3 in the slack channel. I think the only thing that is really needed is a separate Dockerfile, and consequently, separate requirements. But the main bottleneck here is hubble, because tags are not supported there yet, but we would need them for this.

The GPU tests are a good idea. The tricky thing here is that we would want to use GitHub actions for that too, which might be possible by creating a runner on a GPU machine. However, in other projects that use deep learning I have seen them use other CI platforms (Azure pipelines or sth similar).

**Comment by jakob1111996** [comment]
> 
> 
> A jina image with CUDA installed is not possible. Installing CUDA is tricky, and every deep learning framework does it differently (e.g. pytorch uses conda, TF does not).
> 
> Also, for the GPU argument in the executor: also differs across DL frameworks (in pytorch you have "device" for each model, in TF I think you actually have to do it globally). Let's just leave it like that. For that reason, config_gpu etc. is not needed.

I don't think that this is complicated. We can just start with a cuda docker image and then install python3.8 and jina. This is then a jina docker image with GPU support. Tensorflow and Pytorch will then be installed in the executor docker files only, of course.

And about the gpu argument. I know that pytorch and tensorflow have different ways and arguments for handling gpu. We must have some logic in the executors that maps our gpu=True argument to device='cuda', but I think making this parameter the same amongst all executors helps a lot.

**Comment by jakob1111996** [comment]
I talked to @mapleeit , he will be working on tags in hubble next week. Until that, this issue is blocked.

**Comment by tadejsv** [comment]
> And about the gpu argument. I know that pytorch and tensorflow have different ways and arguments for handling gpu. We must have some logic in the executors that maps our gpu=True argument to device='cuda', but I think making this parameter the same amongst all executors helps a lot.

Do we have a `gpu=True` argument? I thought this was Jina 1.x, and was removed. If we have it, I would actually argue for its removal. It's just overpromising.

**Comment by tadejsv** [comment]
> I don't think that this is complicated. We can just start with a cuda docker image and then install python3.8 and jina. This is then a jina docker image with GPU support. Tensorflow and Pytorch will then be installed in the executor docker files only, of course.

Well, you can try if you want - create a docker image with cuda that can serve as a base for pytorch, tensorflow, paddle paddle, mindspore, etc. (jax ?), and where you can install all these frameworks, and GPU support will work out of the box (without reinstalling CUDA). You'll see it's not as easy as it sounds.

**Comment by jakob1111996** [comment]
> Do we have a `gpu=True` argument? I thought this was Jina 1.x, and was removed. If we have it, I would actually argue for its removal. It's just overpromising.

How else would you do it? We need some way of telling the executors to use GPU via an argument. I think gpu=True is more readable than device='cuda' so I would choose something like that.

**Comment by jakob1111996** [comment]
> Well, you can try if you want - create a docker image with cuda that can serve as a base for pytorch, tensorflow, paddle paddle, mindspore, etc. (jax ?), and where you can install all these frameworks, and GPU support will work out of the box (without reinstalling CUDA). You'll see it's not as easy as it sounds.

I have done exactly that for the ImageTFEncoder and TransformerTorchEncoder (plus some more executors) in the past. They are starting on a cuda image, install the requirements - done. If we now create a new image from cuda and install jina called jina/jina:gpu, we can save one step in the executor docker files.

**Comment by tadejsv** [comment]
> > Do we have a `gpu=True` argument? I thought this was Jina 1.x, and was removed. If we have it, I would actually argue for its removal. It's just overpromising.
> 
> How else would you do it? We need some way of telling the executors to use GPU via an argument. I think gpu=True is more readable than device='cuda' so I would choose something like that.

I would use `device='cuda'`. Why would you say it is more readable? Developers knowing pytorch will find it less readable, as it is an unecessary layer of abstraction on top of Pytorch's device managament. And what if I want to specify `device='cuda:1'`?

**Comment by tadejsv** [comment]
> > Well, you can try if you want - create a docker image with cuda that can serve as a base for pytorch, tensorflow, paddle paddle, mindspore, etc. (jax ?), and where you can install all these frameworks, and GPU support will work out of the box (without reinstalling CUDA). You'll see it's not as easy as it sounds.
> 
> I have done exactly that for the ImageTFEncoder and TransformerTorchEncoder (plus some more executors) in the past. They are starting on a cuda image, install the requirements - done. If we now create a new image from cuda and install jina called jina/jina:gpu, we can save one step in the executor docker files.

Well, if that works, then cool

**Comment by jakob1111996** [comment]
> I would use `device='cuda'`. Why would you say it is more readable? Developers knowing pytorch will find it less readable, as it is an unecessary layer of abstraction on top of Pytorch's device managament. And what if I want to specify `device='cuda:1'`?

Multi-GPU setups is a valid argument. We might change the parameter to work with that somehow. I will make sure to make a poll in Slack about the parameter name, so everyone has a say in that 😄

**Comment by tadejsv** [comment]
I think another argument against a general `gpu` property is that it makes developing executors harder: you now need to know about this argument and where to find it, and then transform it to whatever platform specific setting you need to use. We don't really have a great documentation/templates as it is, so I think this would just compound the problem.

**Comment by JoanFM** [comment]
We do not need to add any common parameter between executors. The 2.0 API is about removing boilerplate and giving power back to the user. So every executor may have different parameters to work on gpu. GPU = True is not flexible enough to handle all combinations in my opinion.
