### ISSUE TITLE
Adding retrieving executors

### ISSUE THREAD

**Issue by Ierezell** [jina-ai/executors#60]
**Describe your proposal/problem**

Adding models for retrieving / Question answering like : 
- Dense passage retrieval (DPR)
- Retrieval Augmented generation (Rag)
- Fusion in the decoder (Fid)

They are summarized in this article but appear in many others (https://arxiv.org/pdf/2107.07566.pdf). 

I Finetuned a DPR model (with haystack), which performs quite well. I would like to use it in Jina.
Haystack also has Rag models which are really nice to use. 

As there are Transformer based retrievers (cosine of embeddings) in Jina could we also think about adding those models? 
Else I know there is a convergence of haystack and Jina (https://github.com/jina-ai/jina/issues/2128), could we link them in some way? 

Thanks in advance,
Have a great day.

**Comment by tadejsv** [comment]
Hey @Ierezell , we have just added DRPTextEncoder and DPRReaderRanker executors based on their huggingface implementation!

Take a look and tell us what you think :)
