### ISSUE TITLE
MongoDBIndexer: use .tolist to nparrays

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/executors#88]
Quoting from Slack:

Hey everyone, my colleague just found a bug in your MongoDBIndexer. Please use .tolist() instead of list() for converting a numpy array to a python list:

https://github.com/jina-ai/executors/blob/d943ed10f282081bb4a49ad00617de71fae81dfd/jinahub/indexers/storage/MongoDBStorage/mongo_handler.py#L53

https://github.com/jina-ai/executors/blob/d943ed10f282081bb4a49ad00617de71fae81dfd/jinahub/indexers/storage/MongoDBStorage/mongo_handler.py#L69

Bad:

`item['embedding'] = list(doc.embedding.flatten()) # causes errors when inserting in db, because it creates a list of numpy scalars`

Fix:
`item['embedding'] = doc.embedding.flatten().tolist() # the right way; creates a list of python floats`

Error:
`InvalidDocument("cannot encode object: -0.43712485, of type: <class 'numpy.float32'>")`

**Comment by vivek2301** [comment]
Hi @cristianmtr,

Are these the only changes required or does it needs to be checked in other scripts too?

**Comment by vivek2301** [comment]
Hi @cristianmtr,

Can you help me with an example code to reproduce this bug?
I'll test it and reopen the PR.

**Comment by sauravgarg540** [comment]
Hi @cristianmtr, I would like to work on this issue.

**Comment by cristianmtr** [comment]
Hey @sauravgarg540 

Thanks for the initiative!

We haven't been able to reproduce the issue actually. It was reported to us by one of our EAPs. If you can reproduce it in a test, then we'd appreciate that and the PR to fix it.

**Comment by sauravgarg540** [comment]
Hey @cristianmtr , happy to contribute.

I did some debugging and it doesn't seem like a bug to me. The issue description is correct about the list of `numpy.float` and `python float` but the reason that issue is not reproducible is that embedding is stored as `Double` in the MongoDb and retrieved as `float` from the db.

Please let me know if I am missing something.

**Comment by cristianmtr** [comment]
Then I guess we need to be consistent with the data types. If you can make a PR cleaning that up, it would be appreaciated.

**Comment by sauravgarg540** [comment]
PR created #160

**Comment by cristianmtr** [comment]
Closed by #160
