### ISSUE TITLE
MongoDB: check if embedding before `.pop`

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/executors#92]
https://github.com/jina-ai/executors/blob/d943ed10f282081bb4a49ad00617de71fae81dfd/jinahub/indexers/storage/MongoDBStorage/mongo_handler.py#L87

We have a setup similar to your multireslyrics example. Therefore, the documents indexed by our doc-indexer doesn't have an embedding property. So pop causes an error, because the property doesn't exists. We fixed in internally by a simple if statement:

```
if 'embedding' in result:
    result.pop('embedding')
```

**Comment by sauravgarg540** [comment]
Hi @cristianmtr I have created a [PR](https://github.com/jina-ai/executors/pull/149) in which I have added a unit test case that reproduces the error.

**Comment by cristianmtr** [comment]
Closed by https://github.com/jina-ai/executors/pull/149
